Set title for new chat
mmabrouk/chatgpt-wrapper pull request #112
Opened 2023-02-19 16:14 UTC by thehunmonkgroup

Uses the `/backend-api/conversation/gen_title/[id] POST endpoint`

Note this PR requires PR #109 to function properly.

One optimization that could be made before committing: the POST request is a sync request after the very first message is sent in a new conversation, and the time it takes delays the display of prompt `2>` until the request completes. Once the title is set there is no delay for other messages in the conversation.

Also note that I abstracted an `_api_post_request()` method, and with a little more work, it would be trivial to add other helpful API requests, such as #106.

2023-02-19 16:15 UTC, thehunmonkgroup commented
Note this will fix #110

2023-02-21 15:04 UTC, mmabrouk requested changes
Thanks for fixing the issue! Much appreciated.
I had very minor comments for the code.

2023-02-21 15:04 UTC, mmabrouk commented on chatgpt_wrapper/chatgpt.py
> +        if not self.conversation_id or self.conversation_id and self.conversation_title_set:
it looks like some parenthesis are missing here

2023-02-21 15:04 UTC, mmabrouk commented on chatgpt_wrapper/chatgpt.py
> +        self.conversation_title_set = None
could you please rename this to clarify it's binary:
```suggestion
        self.is_conversation_title_set = False
```

2023-02-21 15:04 UTC, mmabrouk commented on chatgpt_wrapper/chatgpt.py
> +        self.conversation_title_set = None
```suggestion
        self.is_conversation_title_set = False
```

2023-02-21 15:10 UTC, mmabrouk commented
Since I approved the !delete PR which includes this patch, I will close this one and make the minor changed myself on the main branch

2023-02-21 15:10 UTC, closed without merging